### ISSUE TITLE
Does not contain definition for UseOracle

### ISSUE THREAD

**Issue by hmuhdkamran** [ralmsdeveloper/RalmsEntityFrameworkCoreOracle#2]
Dear I am facing an issue `'DbContextOptionsBuilder<OracleContext>' does not contain a definition for 'UseOracle' and no extension method 'UseOracle' accepting a first argument of type 'DbContextOptionsBuilder<OracleContext>' could be found (are you missing a using directive or an assembly reference?)`

**Comment by ralmsdeveloper** [comment]
I will be updating this project this week.

**Comment by hmuhdkamran** [comment]
Sorry to bother but I thing your week contains more than 7 days,

**Comment by ralmsdeveloper** [comment]
True, I've been very busy with company stuff, but I'll be seeing it for tomorrow.

**Comment by Robelind** [comment]
Facing the same problem, but for the non-generic version:

> 'DbContextOptionsBuilder' does not contain a definition for 'UseOracle' and no accessible extension method 'UseOracle' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by sk8Fc** [comment]
In fact, I cannot find the `Ralms.EntityFrameworkCore.Oracle.dll` in your nuget

``` <IncludeBuildOutput>false</IncludeBuildOutput>```

my pull request: #4
