### ISSUE TITLE
What provider name to use when scaffolding

### ISSUE THREAD

**Issue by Robelind** [ralmsdeveloper/RalmsEntityFrameworkCoreOracle#3]
`Scaffold-DbContext "<conn str>" Ralms.EntityFrameworkCore.Oracle`
gives
> Unable to find provider assembly with name Ralms.EntityFrameworkCore.Oracle. Ensure the specified name is correct and is referenced by the project.

I've installed the package through NuGet.

**Comment by odyright** [comment]
Same
